#! /bin/sh

### BEGIN INIT INFO
# Provides:             istatd
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         1
# Short-Description:    iStat Server
### END INIT INFO

DAEMON="/usr/local/bin/istatd"
DAEMON_OPTS="-d"
PID_FILE="/var/run/istat/istatd.pid"

case $1 in
  start) 
    start-stop-daemon --start --pidfile $PID_FILE --background --exec $DAEMON -- $DAEMON_OPTS
    ;;
  stop)
    start-stop-daemon --stop --pidfile $PID_FILE
    ;;
  restart)
    start-stop-daemon --stop --pidfile $PID_FILE
    sleep 1
    start-stop-daemon --start --pidfile $PID_FILE --background --exec $DAEMON -- $DAEMON_OPTS
    ;;
  status)
    if [ -f $PID_FILE ]; then
      echo "istatd is running with pid $(cat $PID_FILE)"
    else
      echo "istatd is not running"
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/istatd {start|stop|restart|status}"
    exit 1
esac

